### ISSUE TITLE
port-forward to hurl does not work

### ISSUE THREAD

**Issue by Cuneytt** [ancientlore/istio-talk#1]
after:
```
kubectl port-forward hurl-6c84f747d9-cfxwq 8082:8080
```
going to http://localhost:8082 throws:
```
Handling connection for 8082
E0319 14:54:50.610997   10770 portforward.go:331] an error occurred forwarding 8082 -> 8080: error forwarding port 8080 to pod 686c2bbd8a2b343eb32e067b53013711b0186b2363722f7abc01dec2b836dcec, uid : exit status 1: 2018/03/19 18:54:50 socat[10027] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```
 webnull is accessible through port 8081.

Thank you very much for the walk-throughs

**Comment by ancientlore** [comment]
Hi - I should make this part more clear. Because hurl is started by the `hurl` command after you `kubectl exec` into the pod, the UI is not available until the command is running. You have to refresh the UI after running `hurl -conns 10 -loop 2000000 http://webnull:8080/xml` inside the container. Let me know if that clears it up.

**Comment by Cuneytt** [comment]
It helped. Thank you
